/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121722-gf2b9b1923d-20251109"
#endif /* AVUTIL_FFVERSION_H */
